api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: 'Imperius Home Automation API'
    description: 'Public API for Imperius Home Automation System'
    version: '0.2.0'
    collection:
        pagination:
            # To enable or disable pagination for all resource collections by default.
            enabled: false
    swagger:
         api_keys:
             - { name: 'Authorization', type: 'header' }
    # Enable the Swagger documentation and export.
    enable_swagger: true

    # Enable Swagger ui.
    enable_swagger_ui: true
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
