version: "2"
services:
    code:
        container_name: code.imperius.home
        build: ./docker/code
        networks:
            - imperius
        volumes:
            - imperius:/code

    web:
        container_name: web.imperius.home
        build: ./docker/nginx
        networks:
            - imperius
        ports:
            - 8089:81
            - 8080:8080
            - 3000:3000
            - 8083:8083
            - 9005:9000
        volumes_from:
            - code
        depends_on:
            - php-fpm-xdebug
            - php-fpm
            - influxdb
            - grafana
            - graylog

    php-fpm:
        container_name: php-fpm.imperius.home
        build: ./docker/php-fpm
        entrypoint:
            - "entrypoint.sh"
            - "php-fpm"
        networks:
            - imperius
        volumes_from:
            - code:delegated

    php-fpm-xdebug:
        container_name: php-fpm-xdebug.imperius.home
        build: ./docker/php-fpm
        entrypoint:
            - "entrypoint.sh"
            - "php-fpm"
            - "-F"
            - "-c"
            - "/xdebug.ini"
        networks:
            - imperius
        volumes_from:
            - code:delegated
        expose:
          - 9001

    mysql:
        container_name: mysql.imperius.home
        build: ./docker/mysql
        networks:
            - imperius
        volumes:
            - imperius-mysql:/var/lib/mysql
        ports:
            - 13333:3306
        environment:
            - MYSQL_DATABASE=imperius
            - MYSQL_USER=imperius-project
            - MYSQL_PASSWORD=imperius-project-pass
            - MYSQL_ROOT_PASSWORD=root

    redis:
        container_name: redis.imperius.home
        build: ./docker/redis
        networks:
            - imperius


    mysql-grafana:
        container_name: mysql-grafana.imperius.home
        build: ./docker/mysql-grafana
        networks:
            - imperius
        environment:
            - MYSQL_DATABASE=grafana
            - MYSQL_USER=imperius-tools
            - MYSQL_PASSWORD=0tMnbuaZULZx66J
            - MYSQL_ROOT_PASSWORD=root

    influxdb:
        container_name: influxdb.imperius.home
        build: ./docker/influxdb
        networks:
            - imperius
        ports:
            - 8086:8086
            - 8084:8083
            - 4444:4444

    grafana:
        container_name: grafana.imperius.home
        build: ./docker/grafana
        depends_on:
            - mysql-grafana
        restart: always
        networks:
            - imperius
        ports:
            - 3002:3000

    telegraf:
        container_name: telegraf.imperius.home
        build: ./docker/telegraf
        depends_on:
            - grafana
        restart: always
        ports:
            - 8125:8125
        networks:
            - imperius

    mongo:
        container_name: mongo.imperius.home
        build: ./docker/mongo
        networks:
            - imperius
        volumes_from:
            - code
        volumes:
            - mongo:/data/db

    elasticsearch:
        container_name: elasticsearch.imperius.home
        build: ./docker/elasticsearch
        command: "elasticsearch -Des.cluster.name='graylog'"
        networks:
            - imperius
        volumes_from:
            - code
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data

    graylog:
        container_name: graylog.imperius.home
        build: ./docker/graylog
        environment:
            GRAYLOG_PASSWORD_SECRET: somepasswordpepper
            GRAYLOG_ROOT_PASSWORD_SHA2: a749771a53dab39ee7c44e12cb73899f63c7fce16f9babd3726aba0ab6143179
            GRAYLOG_WEB_ENDPOINT_URI: http://localhost:9005/api
        depends_on:
            - mongo
            - elasticsearch
        networks:
            - imperius
        volumes_from:
            - code
        ports:
            - 9000:9000
        volumes:
            - graylog-journal:/usr/share/graylog/data/journal
            - graylog-config:/usr/share/graylog/data/config

volumes:
    imperius:
        external: true
    imperius-mysql:
        external: false
    mongo:
        external: false
    elasticsearch:
        external: false
    graylog-journal:
        external: false
    graylog-config:
        external: false

networks:
    imperius:
        external: true
