version: "2"
services:
    code:
        container_name: code.imperius.home
        build: ./docker/code
        networks:
            - imperius
        volumes:
            - imperius:/code

    web:
        container_name: web.imperius.home
        build: ./docker/nginx
        networks:
            - imperius
        ports:
            - 8089:81
            - 8090:80
            - 8888:8888
        volumes_from:
            - code

    php-fpm:
        container_name: php-fpm.imperius.home
        build: ./docker/php-fpm
        entrypoint:
            - "entrypoint.sh"
            - "php-fpm"
        networks:
            - imperius
        volumes_from:
            - code:delegated

    php-fpm-xdebug:
        container_name: php-fpm-xdebug.imperius.home
        build: ./docker/php-fpm
        entrypoint:
            - "entrypoint.sh"
            - "php-fpm"
            - "-F"
            - "-c"
            - "/xdebug.ini"
        networks:
            - imperius
        volumes_from:
            - code:delegated
        expose:
          - 9001

    mysql:
        container_name: mysql.imperius.home
        build: ./docker/mysql
        networks:
            - imperius
        volumes:
            - imperius-mysql:/var/lib/mysql:nocopy
        ports:
            - 13333:3306
        environment:
            - MYSQL_DATABASE=imperius
            - MYSQL_USER=imperius-project
            - MYSQL_PASSWORD=imperius-project-pass
            - MYSQL_ROOT_PASSWORD=root

    redis:
        container_name: redis.imperius.home
        build: ./docker/redis
        networks:
            - imperius


    mysql-grafana:
        container_name: mysql-grafana.imperius.home
        build: ./docker/mysql-grafana
        networks:
            - imperius
        environment:
            - MYSQL_DATABASE=grafana
            - MYSQL_USER=imperius-tools
            - MYSQL_PASSWORD=imperius-tools-pass
            - MYSQL_ROOT_PASSWORD=root

    influxdb:
        container_name: influxdb.imperius.home
        build: ./docker/influxdb
        networks:
            - imperius
        ports:
            - 8086:8086
            - 8083:8083
            - 4444:4444

    grafana:
        container_name: grafana.imperius.home
        build: ./docker/grafana
        depends_on:
            - mysql-grafana
        restart: always
        networks:
            - imperius
        ports:
            - 3000:3000

    telegraf:
        container_name: telegraf.imperius.home
        build: ./docker/telegraf
        depends_on:
            - grafana
        restart: always
        ports:
            - 8125:8125
        networks:
            - imperius

volumes:
    imperius:
        external: true
    imperius-mysql:
        external: true

networks:
    imperius:
        external: true
