version: "2"
services:
    code:
        volumes:
            - imperius:/code:rw
            - ./docker/php-cli/config/custom-config.ini:/usr/local/etc/php/conf.d/custom.ini

volumes:
    imperius:
        external: true
    imperius-mysql:
        external: false