version: "2"
services:
    php-cli:
        container_name: php-cli.imperius.home
        build: ./docker/php-cli
        networks:
            - imperius
        volumes_from:
            - code

    composer:
        container_name: composer.imperius.home
        build: docker/php-cli
        entrypoint: composer
        networks:
            - imperius
        volumes_from:
            - code
        depends_on:
            - code
