version: "2"
services:
    code:
        container_name: code.imperius.home
        build: ./docker/code
        networks:
            - imperius
        volumes:
            - imperius:/code

    web:
        container_name: web.imperius.home
        build: ./docker/nginx
        networks:
            - imperius
        ports:
            - 8089:8081
            - 8090:80
        volumes_from:
            - code

    php-fpm:
        container_name: php-fpm.imperius.home
        build: ./docker/php-fpm
        entrypoint:
            - "entrypoint.sh"
            - "php-fpm"
        networks:
            - imperius
        volumes_from:
            - code:delegated

    php-fpm-xdebug:
        container_name: php-fpm-xdebug.imperius.home
        build: ./docker/php-fpm
        entrypoint:
            - "entrypoint.sh"
            - "php-fpm"
            - "-F"
            - "-c"
            - "/xdebug.ini"
        networks:
            - imperius
        volumes_from:
            - code:delegated
        expose:
          - 9001

    mysql:
        container_name: mysql.imperius.home
        build: ./docker/mysql
        networks:
            - imperius
        volumes:
            - imperius-mysql:/var/lib/mysql:nocopy
        ports:
            - 13333:3306
        environment:
            - MYSQL_DATABASE=imperius
            - MYSQL_USER=imperius-project
            - MYSQL_PASSWORD=imperius-project-pass
            - MYSQL_ROOT_PASSWORD=root

    redis:
        container_name: redis.imperius.home
        build: ./docker/redis
        networks:
            - imperius

volumes:
    imperius:
        external: true
    imperius-mysql:
        external: true

networks:
    imperius:
        external: true
