version: "2"
services:
    php-cli:
        container_name: php-cli.imperius.home
        build: ./docker/php-cli
        networks:
            - imperius
        ports:
          - 8180:80
        volumes_from:
            - code
        depends_on:
          - mysql_unit

    redis-cli:
        container_name: redis-cli.imperius.home
        build: ./docker/redis
        entrypoint:
            - "redis-cli"
            - "-h"
            - "redis"
        networks:
            - imperius
        depends_on:
            - redis

    mysql_unit:
        container_name: mysql-unit.imperius.com
        privileged: true
        build: ./docker/mysql_tmpfs
        networks:
            - imperius
        environment:
            - MYSQLD_RAM_SIZE=512
            - TIMEZONE=Europe/Warsaw

    composer:
        container_name: composer.imperius.home
        build: docker/php-cli
        entrypoint: composer
        networks:
            - imperius
        volumes_from:
            - code
        depends_on:
            - code
