<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BehaviorRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BehaviorRepository extends EntityRepository
{
    public function findAllBySensorId($id)
    {
        $qb = $this->createQueryBuilder('b');
        $qb
            ->where('b.sourceSensor = :id')
            ->setParameter('id', $id)
        ;

        return $qb->getQuery()->getResult();
    }
}
