<?php

namespace App\Repository;

use App\Entity\Sensor;
use App\Repository\Abstraction\BehaviorRepository;

/**
 * BehaviorRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ManualBehaviorRepository extends BehaviorRepository
{
    /**
     * @return array
     */
    public function findAllByActionSensor(Sensor $sensor): array
    {
        $qb = $this->createQueryBuilder('mb');
        $qb->where('mb.actionSensor = :sensor')
            ->setParameter('sensor', $sensor)
        ;

        return $qb->getQuery()->getResult();
    }
}
