<?php

namespace App\Repository;

use App\Repository\Abstraction\BehaviorRepository;

/**
 * BehaviorRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ManualBehaviorRepository extends BehaviorRepository
{
}
