<?php
declare(strict_types=1);
namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class OverviewController extends GenericController
{
    /**
     * @Route("/overview", name="overview")
     */
    public function overviewAction(Request $request)
    {
        

        return $this->getView('index'); // TODO: Change the autogenerated stub
    }
}