<?php
declare(strict_types=1);
namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;

class OverviewController extends GenericController
{
    public function indexAction(Request $request)
    {
        $testArray = [
            "something",
            "other",
            "and",
            "enew",
        ];

        return $this->getView('index', ['test' => $testArray]); // TODO: Change the autogenerated stub
    }
}