<?php
declare(strict_types=1);
namespace App\Controller;

use App\Entity\Room;
use App\Form\RoomType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class RoomController extends GenericController
{
    protected $entityClass = Room::class;

    protected $formType = RoomType::class;


    /**
     * @Route("/room", name="room")
     */
    public function indexAction(Request $request)
    {
        return $this->genericIndexAction($request); // TODO: Change the autogenerated stub
    }

    /**
     * @Route("/room/add", name="room_add")
     */
    public function addAction(Request $request)
    {
        return parent::addAction($request); // TODO: Change the autogenerated stub
    }

    /**
     * @Route("/room/edit/{id}",
     *     name="room_edit",
     *     requirements={
     *     "id": "\d+"
     * })
     */
    public function editAction(Request $request, $id)
    {
        return parent::editAction($request, $id); // TODO: Change the autogenerated stub
    }

    /**
     * @Route("/room/delete/{id}",
     *     name="room_delete",
     *     requirements={
     *     "id": "\d+"
     * })
     */
    public function deleteAction(Request $request, $id)
    {
        return parent::deleteAction($request, $id); // TODO: Change the autogenerated stub
    }
}