<?php
declare(strict_types=1);
namespace App\Controller;

use App\Entity\Sensor;
use App\Form\SensorType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

class SensorController extends GenericController
{
    protected $entityClass = Sensor::class;

    protected $formType = SensorType::class;

    /**
     * @Route("/sensor", name="sensor")
     */
    public function indexAction(Request $request)
    {
        return parent::indexAction($request); // TODO: Change the autogenerated stub
    }

    /**
     * @Route("/sensor/add", name="sensor_add")
     */
    public function addAction(Request $request)
    {
        return parent::addAction($request); // TODO: Change the autogenerated stub
    }

    /**
     * @Route("/sensor/edit/{id}",
     *     name="sensor_edit",
     *     requirements={
     *     "id": "\d+"
     * })
     */
    public function editAction(Request $request, $id)
    {
        return parent::editAction($request, $id); // TODO: Change the autogenerated stub
    }

    /**
     * @Route("/sensor/delete/{id}",
     *     name="sensor_delete",
     *     requirements={
     *     "id": "\d+"
     * })
     */
    public function deleteAction(Request $request, $id)
    {
        return parent::deleteAction($request, $id); // TODO: Change the autogenerated stub
    }

}