<?php
declare(strict_types=1);
namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;

class WelcomeController extends GenericController
{
    public function indexAction(Request $request)
    {
        if ($this->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            return $this->redirectToRoute('overview');
        }

        return parent::indexAction($request); // TODO: Change the autogenerated stub
    }

}