start_page:
    path: /
    defaults: { _controller: 'App\Controller\WelcomeController::indexAction' }

login:
    path: /login
    defaults: { _controller: 'App\Controller\SecurityController::loginAction' }

logout:
    path: /logout

overview:
    path: /overview
    defaults: { _controller: 'App\Controller\OverviewController::indexAction' }

#sensor:
#    path: /sensor
#    defaults: { _controller: 'App\Controller\SensorController::indexAction' }
#
#sensor_add:
#    path: /sensor/add
#    defaults: { _controller: 'App\Controller\SensorController::addAction' }
#
#sensor_edit:
#    path: /sensor/edit/{id}
#    defaults: { _controller: 'App\Controller\SensorController::editAction' }
#
#sensor_delete:
#    path: /sensor/delete/{id}
#    defaults: { _controller: 'App\Controller\SensorController::deleteAction' }
#
#room:
#    path: /room
#    defaults: { _controller: 'App\Controller\RoomController::indexAction' }
#
#room_add:
#    path: /room/add
#    defaults: { _controller: 'App\Controller\RoomController::addAction' }
#
#room_edit:
#    path: /room/edit/{id}
#    defaults: { _controller: 'App\Controller\RoomController::editAction' }
#
#room_delete:
#    path: /room/delete/{id}
#    defaults: { _controller: 'App\Controller\RoomController::deleteAction' }
#
#set_status:
#    path: /sensor/{uuid}/status/set/{status}
#    defaults: { _controller: 'App\Controller\PublishController::setStatusAction' }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile