<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20171113152020 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE alert (id BIGINT AUTO_INCREMENT NOT NULL, version BIGINT NOT NULL, dashboard_id BIGINT NOT NULL, panel_id BIGINT NOT NULL, org_id BIGINT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, message TEXT NOT NULL COLLATE utf8mb4_unicode_ci, state VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, settings TEXT NOT NULL COLLATE utf8mb4_unicode_ci, frequency BIGINT NOT NULL, handler BIGINT NOT NULL, severity TEXT NOT NULL COLLATE utf8mb4_unicode_ci, silenced TINYINT(1) NOT NULL, execution_error TEXT NOT NULL COLLATE utf8mb4_unicode_ci, eval_data TEXT DEFAULT NULL COLLATE utf8mb4_unicode_ci, eval_date DATETIME DEFAULT NULL, new_state_date DATETIME NOT NULL, state_changes INT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_alert_org_id_id (org_id, id), INDEX IDX_alert_state (state), INDEX IDX_alert_dashboard_id (dashboard_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alert_notification (id BIGINT AUTO_INCREMENT NOT NULL, org_id BIGINT NOT NULL, name VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, settings TEXT NOT NULL COLLATE utf8mb4_unicode_ci, created DATETIME NOT NULL, updated DATETIME NOT NULL, is_default TINYINT(1) DEFAULT \'0\' NOT NULL, UNIQUE INDEX UQE_alert_notification_org_id_name (org_id, name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE annotation (id BIGINT AUTO_INCREMENT NOT NULL, org_id BIGINT NOT NULL, alert_id BIGINT DEFAULT NULL, user_id BIGINT DEFAULT NULL, dashboard_id BIGINT DEFAULT NULL, panel_id BIGINT DEFAULT NULL, category_id BIGINT DEFAULT NULL, type VARCHAR(25) NOT NULL COLLATE utf8mb4_unicode_ci, title TEXT NOT NULL COLLATE utf8mb4_unicode_ci, text TEXT NOT NULL COLLATE utf8mb4_unicode_ci, metric VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, prev_state VARCHAR(25) NOT NULL COLLATE utf8mb4_unicode_ci, new_state VARCHAR(25) NOT NULL COLLATE utf8mb4_unicode_ci, data TEXT NOT NULL COLLATE utf8mb4_unicode_ci, epoch BIGINT NOT NULL, region_id BIGINT DEFAULT 0, INDEX IDX_annotation_org_id_alert_id (org_id, alert_id), INDEX IDX_annotation_org_id_type (org_id, type), INDEX IDX_annotation_org_id_category_id (org_id, category_id), INDEX IDX_annotation_org_id_dashboard_id_panel_id_epoch (org_id, dashboard_id, panel_id, epoch), INDEX IDX_annotation_org_id_epoch (org_id, epoch), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE api_key (id BIGINT AUTO_INCREMENT NOT NULL, org_id BIGINT NOT NULL, name VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, `key` VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, role VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UQE_api_key_key (`key`), UNIQUE INDEX UQE_api_key_org_id_name (org_id, name), INDEX IDX_api_key_org_id (org_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dashboard (id BIGINT AUTO_INCREMENT NOT NULL, version INT NOT NULL, slug VARCHAR(189) NOT NULL COLLATE utf8mb4_unicode_ci, title VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, data MEDIUMTEXT NOT NULL COLLATE utf8mb4_unicode_ci, org_id BIGINT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, updated_by INT DEFAULT NULL, created_by INT DEFAULT NULL, gnet_id BIGINT DEFAULT NULL, plugin_id VARCHAR(189) DEFAULT NULL COLLATE utf8mb4_unicode_ci, UNIQUE INDEX UQE_dashboard_org_id_slug (org_id, slug), INDEX IDX_dashboard_org_id (org_id), INDEX IDX_dashboard_gnet_id (gnet_id), INDEX IDX_dashboard_org_id_plugin_id (org_id, plugin_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dashboard_snapshot (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, `key` VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, delete_key VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, org_id BIGINT NOT NULL, user_id BIGINT NOT NULL, external TINYINT(1) NOT NULL, external_url VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, dashboard MEDIUMTEXT NOT NULL COLLATE utf8mb4_unicode_ci, expires DATETIME NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UQE_dashboard_snapshot_key (`key`), UNIQUE INDEX UQE_dashboard_snapshot_delete_key (delete_key), INDEX IDX_dashboard_snapshot_user_id (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dashboard_tag (id BIGINT AUTO_INCREMENT NOT NULL, dashboard_id BIGINT NOT NULL, term VARCHAR(50) NOT NULL COLLATE utf8mb4_unicode_ci, INDEX IDX_dashboard_tag_dashboard_id (dashboard_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dashboard_version (id BIGINT AUTO_INCREMENT NOT NULL, dashboard_id BIGINT NOT NULL, parent_version INT NOT NULL, restored_from INT NOT NULL, version INT NOT NULL, created DATETIME NOT NULL, created_by BIGINT NOT NULL, message TEXT NOT NULL COLLATE utf8mb4_unicode_ci, data MEDIUMTEXT DEFAULT NULL COLLATE utf8mb4_unicode_ci, UNIQUE INDEX UQE_dashboard_version_dashboard_id_version (dashboard_id, version), INDEX IDX_dashboard_version_dashboard_id (dashboard_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE data_source (id BIGINT AUTO_INCREMENT NOT NULL, org_id BIGINT NOT NULL, version INT NOT NULL, type VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, access VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, url VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, password VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, user VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, `database` VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, basic_auth TINYINT(1) NOT NULL, basic_auth_user VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, basic_auth_password VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, is_default TINYINT(1) NOT NULL, json_data TEXT DEFAULT NULL COLLATE utf8mb4_unicode_ci, created DATETIME NOT NULL, updated DATETIME NOT NULL, with_credentials TINYINT(1) DEFAULT \'0\' NOT NULL, secure_json_data TEXT DEFAULT NULL COLLATE utf8mb4_unicode_ci, UNIQUE INDEX UQE_data_source_org_id_name (org_id, name), INDEX IDX_data_source_org_id (org_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE migration_log (id BIGINT AUTO_INCREMENT NOT NULL, migration_id VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, `sql` TEXT NOT NULL COLLATE utf8mb4_unicode_ci, success TINYINT(1) NOT NULL, error TEXT NOT NULL COLLATE utf8mb4_unicode_ci, timestamp DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE org (id BIGINT AUTO_INCREMENT NOT NULL, version INT NOT NULL, name VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, address1 VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, address2 VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, city VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, state VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, zip_code VARCHAR(50) DEFAULT NULL COLLATE utf8mb4_unicode_ci, country VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, billing_email VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UQE_org_name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE org_user (id BIGINT AUTO_INCREMENT NOT NULL, org_id BIGINT NOT NULL, user_id BIGINT NOT NULL, role VARCHAR(20) NOT NULL COLLATE utf8mb4_unicode_ci, created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UQE_org_user_org_id_user_id (org_id, user_id), INDEX IDX_org_user_org_id (org_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE playlist (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, `interval` VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, org_id BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE playlist_item (id BIGINT AUTO_INCREMENT NOT NULL, playlist_id BIGINT NOT NULL, type VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, value TEXT NOT NULL COLLATE utf8mb4_unicode_ci, title TEXT NOT NULL COLLATE utf8mb4_unicode_ci, `order` INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE plugin_setting (id BIGINT AUTO_INCREMENT NOT NULL, org_id BIGINT DEFAULT NULL, plugin_id VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, enabled TINYINT(1) NOT NULL, pinned TINYINT(1) NOT NULL, json_data TEXT DEFAULT NULL COLLATE utf8mb4_unicode_ci, secure_json_data TEXT DEFAULT NULL COLLATE utf8mb4_unicode_ci, created DATETIME NOT NULL, updated DATETIME NOT NULL, plugin_version VARCHAR(50) DEFAULT NULL COLLATE utf8mb4_unicode_ci, UNIQUE INDEX UQE_plugin_setting_org_id_plugin_id (org_id, plugin_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE preferences (id BIGINT AUTO_INCREMENT NOT NULL, org_id BIGINT NOT NULL, user_id BIGINT NOT NULL, version INT NOT NULL, home_dashboard_id BIGINT NOT NULL, timezone VARCHAR(50) NOT NULL COLLATE utf8mb4_unicode_ci, theme VARCHAR(20) NOT NULL COLLATE utf8mb4_unicode_ci, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quota (id BIGINT AUTO_INCREMENT NOT NULL, org_id BIGINT DEFAULT NULL, user_id BIGINT DEFAULT NULL, target VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, `limit` BIGINT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UQE_quota_org_id_user_id_target (org_id, user_id, target), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE session (`key` CHAR(16) NOT NULL COLLATE utf8mb4_unicode_ci, data BLOB NOT NULL, expiry INT NOT NULL, PRIMARY KEY(`key`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE star (id BIGINT AUTO_INCREMENT NOT NULL, user_id BIGINT NOT NULL, dashboard_id BIGINT NOT NULL, UNIQUE INDEX UQE_star_user_id_dashboard_id (user_id, dashboard_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE temp_user (id BIGINT AUTO_INCREMENT NOT NULL, org_id BIGINT NOT NULL, version INT NOT NULL, email VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, role VARCHAR(20) DEFAULT NULL COLLATE utf8mb4_unicode_ci, code VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, status VARCHAR(20) NOT NULL COLLATE utf8mb4_unicode_ci, invited_by_user_id BIGINT DEFAULT NULL, email_sent TINYINT(1) NOT NULL, email_sent_on DATETIME DEFAULT NULL, remote_addr VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_temp_user_email (email), INDEX IDX_temp_user_org_id (org_id), INDEX IDX_temp_user_code (code), INDEX IDX_temp_user_status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_data (id INT AUTO_INCREMENT NOT NULL, metric1 VARCHAR(20) DEFAULT NULL COLLATE utf8mb4_unicode_ci, metric2 VARCHAR(150) DEFAULT NULL COLLATE utf8mb4_unicode_ci, value_big_int BIGINT DEFAULT NULL, value_double DOUBLE PRECISION DEFAULT NULL, value_float DOUBLE PRECISION DEFAULT NULL, value_int INT DEFAULT NULL, time_epoch BIGINT NOT NULL, time_date_time DATETIME NOT NULL, time_time_stamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id BIGINT AUTO_INCREMENT NOT NULL, version INT NOT NULL, login VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, email VARCHAR(190) NOT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, password VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, salt VARCHAR(50) DEFAULT NULL COLLATE utf8mb4_unicode_ci, rands VARCHAR(50) DEFAULT NULL COLLATE utf8mb4_unicode_ci, company VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, org_id BIGINT NOT NULL, is_admin TINYINT(1) NOT NULL, email_verified TINYINT(1) DEFAULT NULL, theme VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, created DATETIME NOT NULL, updated DATETIME NOT NULL, help_flags1 BIGINT DEFAULT 0 NOT NULL, UNIQUE INDEX UQE_user_login (login), UNIQUE INDEX UQE_user_email (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE alert');
        $this->addSql('DROP TABLE alert_notification');
        $this->addSql('DROP TABLE annotation');
        $this->addSql('DROP TABLE api_key');
        $this->addSql('DROP TABLE dashboard');
        $this->addSql('DROP TABLE dashboard_snapshot');
        $this->addSql('DROP TABLE dashboard_tag');
        $this->addSql('DROP TABLE dashboard_version');
        $this->addSql('DROP TABLE data_source');
        $this->addSql('DROP TABLE migration_log');
        $this->addSql('DROP TABLE org');
        $this->addSql('DROP TABLE org_user');
        $this->addSql('DROP TABLE playlist');
        $this->addSql('DROP TABLE playlist_item');
        $this->addSql('DROP TABLE plugin_setting');
        $this->addSql('DROP TABLE preferences');
        $this->addSql('DROP TABLE quota');
        $this->addSql('DROP TABLE session');
        $this->addSql('DROP TABLE star');
        $this->addSql('DROP TABLE temp_user');
        $this->addSql('DROP TABLE test_data');
        $this->addSql('DROP TABLE user');
    }
}
